{

  "before_install": [],
  "cache": {
    "directories": [
      "$HOME/.m2"
    ]
  },
  "jdk": "oraclejdk8",
  "language": "java",
  "script": "./mvnw test-compile -Dgpg.skip=true -Dlicense.skip=true",
  "sudo": "false",
  "group": "stable",
  "dist": "precise",
  "os": "linux"
} 
